[package]
name = "advent_of_code_2015"
version = "0.1.0"
authors = ["Vincent Lee <vincent.lee@outlook.com>"]
edition = "2018"

[dependencies]
itertools = "0.8"
rust-crypto = "0.2"
pcre = "0.2"
regex = "1"
serde_json = "1"
